app:
    resource: "@System/Controller/"
    type:     annotation

traders:
    resource: "@Traders/Controller/"
    type:     annotation
    prefix: /api/traders

partners:
    resource: "@Partners/Controller/"
    type:     annotation
    prefix: /api/partners
