# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        traders:
            pattern: ^/
            anonymous: ~
            access_denied_url: '/api/traders/login'
            entry_point: security.tradersEntryPoint
            http_basic:
                realm: "Secured Traders Area"
            logout:
              path:   /logout
              target: /
    access_control:
        - { path: ^/api/traders/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/traders/*, roles: ROLE_TRADER  }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }
    encoders:
        System\Entity\Traders:
            algorithm: sha1
            cost: 16

    role_hierarchy:
        ROLE_TRADER: ROLE_TRADER
        ROLE_ADMIN: [ ROLE_TRADER ]

    providers:
        customers:
            entity: { class: System:Traders, property: email }